 const Products=[
    {
        _id:1,
        name:'Ashaway Badimintion Racket',
        image:'/images/ashaway.jpeg',
        description:'Badmintion Racket for advanced players built in by carbon',
        brand: 'Ashaway',
        price: 40,
        countInStock:0,
        rating:4.5,
        numReviews:4,
    },{
        _id:2,
        name: 'Tennis Racket',
        image:'/images/tennis1.jpeg',
        description:'Tennis Racket for advanced players built in by carbon',
        brand: 'Sg',
        price: 75,
        countInStock:2,
        rating:2,
        numReviews:3,
    },{
        _id:3,
        name:'Ashaway Badimintion Racket',
        image:'/images/tennis2.jpeg',
        description:'tennis Racket for Intermidiate players built in by carbon',
        brand: 'Gk',
        price: 80,
        countInStock:3,
        rating:4.5,
        numReviews:4,
    },{
        _id:4,
        name:'Yonex Badimintion Racket',
        image:'/images/yonex.jpeg',
        description:'Badmintion Racket for advanced players built in by carbon',
        brand: 'Ashaway',
        price: 40,
        countInStock:5,
        rating:4,
        numReviews:2,
    },{
        _id:5,
        name:'Yonex Badimintion Racket',
        image:'/images/yonex1.jpeg',
        description:'Badmintion Racket for advanced players built in by carbon',
        brand: 'Yonex',
        price: 40,
        countInStock:3,
        rating:4.5,
        numReviews:4,
    },
]
export default Products